Scrap script for Edsitement's web site
learningequality/sushi-chef-edsitement pull request #1
Opened 2017-12-01 00:14 UTC by elaeon

2017-12-01 18:52 UTC, ivanistheone requested changes
first pass of comments

2017-12-01 18:52 UTC, ivanistheone commented on souschef.py
> +def scrap_lesson_plans():
Global change `scrap` --> `scrape`, think scraping tasty good stuff from the bottom of a cooking pan.

2017-12-01 18:52 UTC, ivanistheone commented on souschef.py
> +    from urllib.parse import urlparse
these two imports could be at the top

2017-12-01 21:29 UTC, jayoshih requested changes
Looks awesome! Really great use of classes and really clear coding. Just a couple of requests, and it should be good to merge

2017-12-01 21:29 UTC, jayoshih commented on souschef.py
> +STUDENT_RESOURCE_TOPIC_INIT = 0#0
Could you add comments on what these constants are used for?

2017-12-01 21:29 UTC, jayoshih commented on souschef.py
> +    subject_ids = [25, 21, 22, 23]#, 18319, 18373, 25041, 31471]
Is there a way to extract these from the page? Not sure if these get updated

2017-12-01 21:29 UTC, jayoshih commented on souschef.py
> +    def get_content(self):
To avoid repetition of code, maybe add this method to the base class and set a class attribute like `content_tag='p'` or `content_tag='ul'` to use on `content = content.findChildren(self.content_tag)` then just override in subclasses that don't follow this pattern

2017-12-02 05:19 UTC, elaeon commented on souschef.py
> +    def get_content(self):
It's a good idea, and I realized that content.findChildren is not necessary. I dropped it and now all get_content methods are the same :)

2017-12-02 05:31 UTC, elaeon commented on souschef.py
> +    subject_ids = [25, 21, 22, 23]#, 18319, 18373, 25041, 31471]
I didn't find a robust pattern to extract these ids, but I think the ids not change.

2017-12-02 17:26 UTC, ivanistheone approved these changes

2017-12-02 17:28 UTC, ivanistheone commented
This one looks ready to merge or did you plan to make any further changes?

I'll merge later this afternoon and run it on our server.

2017-12-02 17:32 UTC, elaeon commented
Hi Ivan,

I don't plan to make any changes.



2017-12-02 11:28 GMT-06:00 Ivan Savov <notifications@github.com>:

> This one looks ready to merge or did you plan to make any further changes?
>
> I'll merge later this afternoon and run it on our server.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/sushi-chef-edsitement/pull/1#issuecomment-348706619>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABKRdAwW2LtYac92EUpoFUZaT8Sa2Itjks5s8YitgaJpZM4Qxrfv>
> .
>

2017-12-02 17:34 UTC, merged